name: Build and zip

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build exe file
        run: |
          pyinstaller --distpath . --name soundboard --noconsole --onefile ./src/main.py

      - name: Zip file
        run: |
          zip -r soundboard.zip . -i .LICENSE .audio .README.md .soundboard.exe

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: soundboard
          path: soundboard.zip

      - name: Add artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./soundboard.zip
          asset_name: soundboard.zip
          asset_content_type: application/zip
